services:
  windows:
    image: dockurr/windows
    container_name: windows
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    restart: on-failure
    volumes:
      # Please start with an empty /storage folder: rm -fr /var/win/*
      # install a different version of Windows
      # - /home/$USER/VirtualMachines/Windows-Docker/windows.iso:/custom.iso
      - /var/win:/storage
      - /home/$USER/Public:/shared
    environment:
      # VERSION: "win11e"
      USERNAME: "Quickemu"
      PASSWORD: "quickemu"
      RAM_SIZE: "3G"
      CPU_CORES: "3"
      DISK_SIZE: "64G"
