services:
  redroid:
    image: erstt/redroid:15.0.0_ndk_magisk_litegapps_AVD
    container_name: redroid-android
    deploy:
      resources:
        limits:
          memory: 2G
    mem_limit: 2G
    memswap_limit: 6G
    tty: true
    stdin_open: true
    privileged: true
    cap_add:
      - NET_ADMIN
    ports:
      - 5552:5555/tcp
      - 5900:5900/udp
    stop_grace_period: 2m
    restart: on-failure
    volumes:
      - /var/redroid:/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    command:
      - androidboot.redroid_width=1600
      - androidboot.redroid_height=1600
      - androidboot.redroid_dpi=480
      - androidboot.redroid_fps=60
      - androidboot.redroid_gpu_mode=host
      - androidboot.use_memfd=1
      - redroid.vncserver=1
      - ro.product.cpu.abilist=x86_64,arm64-v8a,x86,armeabi-v7a,armeabi
      - ro.product.cpu.abilist64=x86_64,arm64-v8a
      - ro.product.cpu.abilist32=x86,armeabi-v7a,armeabi
      - ro.dalvik.vm.isa.arm=x86
      - ro.dalvik.vm.isa.arm64=x86_64
      - ro.enable.native.bridge.exec=1
      - ro.enable.native.bridge.exec64=1
      - ro.vendor.enable.native.bridge.exec=1
      - ro.vendor.enable.native.bridge.exec64=1
      - ro.dalvik.vm.native.bridge=libhoudini.so
