services:
  zerobyte:
    image: ghcr.io/nicotsx/zerobyte:v0.36
    container_name: zerobyte
    ports:
      - "4096:4096"
    stop_grace_period: 2m
    restart: unless-stopped

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/lib/zerobyte:/var/lib/zerobyte
      - ~/linux-setup/:/linux-setup
      - ~/Public/Notes/:/Notes
      - /var/redroid/:/redroid-android11
      - /opt/redroid/:/redroid-android15

    environment:
      - TZ=Europe/Moscow
      - BASE_URL=http://localhost:4096
      - APP_SECRET_FILE=/run/secrets/app_secret
      - ~/.config/rclone:/root/.config/rclone:ro

    secrets:
      - app_secret

secrets:
  app_secret:
    file: ./secrets/app_secret.txt
