#!/bin/sh

# (Probably) you
# don't need a display manager

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# xsetroot -cursor_name left_ptr &
xsetroot -xcf /usr/share/icons/Afterglow-Recolored-Gruvbox-Black/cursors/left_ptr 32

# merge in defaults and keymaps
if [ -f $sysresources ]; then
    xrdb -I $HOME -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# send F13 for left Shift, right Control
xcape -e 'Control_L=Escape;Shift_L=F13;Control_R=F13' &

# pointer
xbanish -s -t2 -i all &

# Keyring
eval $(/usr/bin/gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh)
export $(gnome-keyring-daemon --start --components=pkcs11,secrets,ssh,gpg)
dbus-update-activation-environment --systemd DISPLAY

# compositor
# /usr/bin/picom -b &

# Start applets, daemons, etc.
# diskie
# nm-applet
# ...

# To be able to use gnome-keyring
f="/etc/X11/xinit/xinitrc.d/50-systemd-user.sh"; [[ -f "$f" ]] && source "$f"
# Start i3wm
exec i3
