#!/bin/sh

# dpi
xrandr --dpi 96

# set keyboard repeat rate
xset r rate 350 55

# screensaver off
xset s off
xset -dpms
xset r off

# multimedia
mount -a &
mopidy &

# bluetooth
bluetoothctl power off &

# bell
xset b off

# font
xset +fp ~/.fonts
xset fp rehash
fc-cache -fv &

# pointer
xbanish -s -t3 -i all &
xsetroot -xcf /usr/share/icons/Afterglow-Recolored-Gruvbox-Black/cursors/left_ptr 32

# (Probably) you
# don't need a display manager

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps
if [ -f $sysresources ]; then
  xrdb -I $HOME -merge $sysresources
fi

if [ -f $sysmodmap ]; then
  xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
  xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
  xmodmap "$usermodmap"
fi

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# F13 for LShift & RControl
xcape -e 'Control_L=Escape;Shift_L=F13;Shift_R=F13;Control_R=F13' &

# Keyring
eval "$(/usr/bin/gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh)"
export SSH_AUTH_SOCK
export GPG_AGENT_INFO
export GNOME_KEYRING_CONTROL
export GNOME_KEYRING_PID

# auth
f="/etc/X11/xinit/xinitrc.d/50-systemd-user.sh"
[[ -f "$f" ]] && source "$f"

# Start applets, daemons, etc.
# watcher

# redshift
redshift-gtk -l 0.314757:32.577754 &

# mega
megasync &

# watcher
aw-qt &

# terminal
urxvtd -q &

# nm-applet
# ...

# compositor
picom --experimental-backends --backend glx -b &

# Start i3wm
exec i3
