windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAAAAAAAAAAABNQAAAK3AAACcwAAAA4AAATGAAACqAAAAAAABAAABNUAAAAAAAAA
    AAAABNQAAAK3
  tabs:
  - history:
    - active: true
      last_visited: '2023-10-11T14:18:37'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: 'GitHub - BurntSushi/ripgrep: ripgrep recursively searches directories
        for a regex pattern while respecting your gitignore'
      url: https://github.com/BurntSushi/ripgrep
      zoom: 0.9
  - history:
    - active: true
      last_visited: '2023-10-11T14:18:35'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Install ripgrep on Ubuntu · GitHub
      url: https://gist.github.com/kostaz/6e0cf1eee35a34cd6589ec15b58e682c
      zoom: 0.9
  - history:
    - active: true
      last_visited: '2023-10-11T14:18:33'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: scrcpy/doc/linux.md at master · Genymobile/scrcpy · GitHub
      url: https://github.com/Genymobile/scrcpy/blob/master/doc/linux.md
      zoom: 0.9
  - history:
    - active: true
      last_visited: '2023-10-11T14:18:30'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Zimbra Web Client Sign In
      url: https://webmail.netisgroup.net/#1
      zoom: 0.9
  - history:
    - active: true
      last_visited: '2023-10-11T14:18:30'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: 'From zsh to fish: A Complete Setup Guide'
      url: https://reckoning.dev/blog/fish-shell/
      zoom: 0.9
  - history:
    - active: true
      last_visited: '2023-10-11T14:18:31'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Install VisiData | VisiData
      url: https://www.visidata.org/install/
      zoom: 0.9
  - history:
    - active: true
      last_visited: '2023-10-11T14:18:29'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: 'slime time: Replacing RStudio/Jupyter with vim-slime/tmux? | Formerly
        www.nickthoughts.gov.www\nickthoughts'
      url: http://nicksun.fun/linux/2020/07/06/slime-time.html
      zoom: 0.9
  - active: true
    history:
    - active: true
      last_visited: '2023-10-11T16:08:30'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: 'GitHub - hoehermann/purple-gowhatsapp: Pidgin/libpurple plugin for WhatsApp
        Web.'
      url: https://github.com/hoehermann/purple-gowhatsapp
      zoom: 0.9
