windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAAAAAAAAAAABNQAAAK3AAAAAAAAAAAAAATUAAACtwAAAAAAAAAABNUAAAAAAAAA
    AAAABNQAAAK3
  tabs:
  - history:
    - active: true
      last_visited: '2023-11-09T12:52:13'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: 'GitHub - MilesCranmer/vim-stream: vims - use vim like sed'
      url: https://github.com/MilesCranmer/vim-stream
      zoom: 0.9
  - history:
    - active: true
      last_visited: '2023-11-09T12:52:14'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: 'GitHub - BurntSushi/ripgrep: ripgrep recursively searches directories
        for a regex pattern while respecting your gitignore'
      url: https://github.com/BurntSushi/ripgrep
      zoom: 0.9
  - history:
    - active: true
      last_visited: '2023-11-09T12:52:13'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: scrcpy/doc/control.md at master · Genymobile/scrcpy · GitHub
      url: https://github.com/Genymobile/scrcpy/blob/master/doc/control.md
      zoom: 0.9
  - history:
    - active: true
      last_visited: '2023-11-09T12:52:09'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Install VisiData | VisiData
      url: https://www.visidata.org/install/
      zoom: 0.9
  - history:
    - active: true
      last_visited: '2023-11-09T12:52:14'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: 'GitHub - Vigemus/iron.nvim: Interactive Repl Over Neovim'
      url: https://github.com/Vigemus/iron.nvim
      zoom: 0.9
  - history:
    - active: true
      last_visited: '2023-11-09T12:52:09'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: linux - tmux disregarding the configuration file - Super User
      url: https://superuser.com/questions/188491/tmux-disregarding-the-configuration-file
      zoom: 0.9
  - history:
    - active: true
      last_visited: '2023-11-09T12:52:09'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Install Docker Engine on Ubuntu | Docker Docs
      url: https://docs.docker.com/engine/install/ubuntu/
      zoom: 0.9
  - history:
    - active: true
      last_visited: '2023-11-09T12:52:14'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: 'GitHub - antkr10/tex-cvbuilder: Collection of customizable CV & cover
        letter LaTeX templates'
      url: https://github.com/antkr10/tex-cvbuilder
      zoom: 0.9
  - history:
    - active: true
      last_visited: '2023-11-09T12:52:13'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: 'GitHub - kholia/OSX-KVM: Run macOS on QEMU/KVM. With OpenCore + Big
        Sur + Monterey + Ventura support now! Only commercial (paid) support is available
        now to avoid spammy issues. No Mac system is required.'
      url: https://github.com/kholia/OSX-KVM
      zoom: 0.9
  - history:
    - active: true
      last_visited: '2023-11-09T12:52:13'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: 'GitHub - sickcodes/osx-optimizer: OSX Optimizer: Optimize MacOS - Shell
        scripts to speed up your mac boot time, accelerate loading, and prevent unnecessary
        throttling.'
      url: https://github.com/sickcodes/osx-optimizer
      zoom: 0.9
  - active: true
    history:
    - active: true
      last_visited: '2023-11-09T12:52:14'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Download - Obsidian
      url: https://obsidian.md/download
      zoom: 0.9
