services:
    redroid:
        stdin_open: true
        tty: true
        privileged: true
        volumes:
            - /var/droid:/storage
        ports:
            - 5555:5555
        image: redroid/redroid:11.0.0_gapps_ndk_magisk_widevine
        command:
            - ro.product.cpu.abilist=x86_64,arm64-v8a,x86,armeabi-v7a,armeabi
            - ro.product.cpu.abilist64=x86_64,arm64-v8a
            - ro.product.cpu.abilist32=x86,armeabi-v7a,armeabi
            - ro.dalvik.vm.isa.arm=x86 ro.dalvik.vm.isa.arm64=x86_64
            - ro.enable.native.bridge.exec=1
            - ro.dalvik.vm.native.bridge=libndk_translation.so
            - ro.ndk_translation.version=0.2.2
            # Enable GPU hardware acceleration.
            # - androidboot.redroid_gpu_mode=auto
