services:
     redroid:
       # image: redroid/redroid:11.0.0_gapps_ndk_magisk_widevine
       image: redroid/redroid:11.0.0_gapps_ndk_magisk
       stdin_open: true
       tty: true
       privileged: true
       ports:
       # - "5555:5555"
       - 11101:5555
       volumes:
       # Data storage
       - ./redroid-11-data:/data
       - /etc/localtime:/etc/localtime:ro
       - /etc/timezone:/etc/timezone:ro
       command:
       # Android resolution
       # - androidboot.redroid_width=720
       # - androidboot.redroid_height=1280
       - androidboot.redroid_dpi=320
       # Enable host GPU hardware acceleration
       - androidboot.redroid_gpu_mode=host
       # Set libndk parameters
       - ro.product.cpu.abilist0=x86_64,arm64-v8a,x86,armeabi-v7a,armeabi
       - ro.product.cpu.abilist64=x86_64,arm64-v8a
       - ro.product.cpu.abilist32=x86,armeabi-v7a,armeabi
       - ro.dalvik.vm.isa.arm=x86
       - ro.dalvik.vm.isa.arm64=x86_64
       - ro.enable.native.bridge.exec=1
       - ro.dalvik.vm.native.bridge=libndk_translation.so
       - ro.ndk_translation.version=0.2.2
